Squashed 'helpers/' changes from 5049adf..149b44a
149b44a VFS-1450 Update clproto.
3483f26 VFS-1398 Change ProxyIORequest.space_id to ProxyIORequest.file_uuid.
10384fc Merge pull request #99 in VFS/clproto from feature/VFS-1398-cdmi-metadata to develop
0856cbb Merge pull request #97 in VFS/clproto from feature/VFS-1371-clusterproxy-storage-helper to develop
8afb7e1 VFS-1371 Add SpaceId to GetHelperParams and FileLocation.
2e82140 VFS-1371 Add space_id to ProxyIORequest.
e095c2e Merge remote-tracking branch 'origin/feature/VFS-1371-clusterproxy-storage-helper_merge' into feature/VFS-1371-clusterproxy-storage-helper
aa81caa Merge remote-tracking branch 'origin/develop' into feature/VFS-1371-clusterproxy-storage-helper
d1bfbca VFS-1398 Rename xattr.key to xattr.name.
6b4c704 VFS-1398 Add xattr messages to possible fuse messages.
4a969b5 Merge branch 'feature/VFS-1407-client-get-subscriptions-on-handshake' into feature/VFS-1398-cdmi-metadata
e640bcc VFS-1398 Add xattr messages.
8ac886e VFS-1407 Getting subscriptions on handshake response.
a68b34f Merge remote-tracking branch 'origin/develop' into feature/VFS-1371-clusterproxy-storage-helper
5bae72d VFS-1371 Remove SpaceID from ProxyIO arguments.
7e5d95b VFS-1371 Add POSIX error codes.
a9da5c4 VFS-1289 Enable NIF library build.
4b9a5e0 VFS-1289 Fix compilation errors of NIF libs.
277fd05 Merge branch 'feature/VFS-1371-clusterproxy-storage-helper_merge' into feature/VFS-1371-clusterproxy-storage-helper
2d49007 VFS-1371 Add protocol messages for ProxyIO helper.
b11995b Merge pull request #96 in VFS/clproto from feature/VFS-1289-event-manager-for-one-client-v.3.0 to develop
e78734c VFS-1289 Add message that can carry multiple events of the same type.
00e73be Merge pull request #95 in VFS/clproto from feature/VFS-1289-event-manager-for-one-client-v.3.0 to develop
f7f9162 VFS-1289 Make stream ID optional in MessageStreamReset message.
863b0ca VFS-1289 Change type of subscription ID from unsigned to signed integer.
409c062 VFS-1289 Add stream ID to stream reset message.
6498a3f VFS-1289 Change name of 'oneof' constructions in event messages.
7456587 VFS-1289 Enable NIF library build.
e547efc VFS-1289 New events multilayer architecture. Unit and integration tests extension.
24bc3db VFS-1289 Fix compilation errors of NIF libs.
33b7776 Merge commit '1a1105c65d9a2e13d99effa9d9f331beb6ba93b1' into feature/VFS-1289-event-manager-for-one-client-v.3.0
6891efe VFS-1289 Implement sequencer behaviour.
a52d053 Merge remote-tracking branch 'origin/develop' into feature/VFS-1235-operations-on-files-at-the-client
d606115 Merge pull request #93 in VFS/clproto from feature/VFS-1235-operations-on-files-at-the-client to develop
1eac08d Merge remote-tracking branch 'origin/develop' into feature/VFS-1235-operations-on-files-at-the-client
164b577 Merge pull request #89 in VFS/clproto from feature/VFS-1223-implementation-of-macaroons-for to develop
4af31f8 VFS-1235 Implement truncate.
20b8d05 VFS-1235 Implement truncate.
446bef1 VFS-1223 Add a refreshing macaroons capability.
4dbd2e5 Merge pull request #88 in VFS/clproto from feature/VFS-1217-optimization-of-development-environment to develop
4239d9d VFS-1217 Generate clproto erl files only if not yet generated.
f9d0890 Merge remote-tracking branch 'origin/feature/VFS-1223-implementation-of-macaroons-for_merge' into feature/VFS-1223-implementation-of-macaroons-for
d0fdb94 VFS-1217 Clear environment compilation flags.
49787dd Merge remote-tracking branch 'origin/develop' into feature/VFS-1217-optimization-of-development-environment
b3f0853 VFS-1223 Add a refreshing macaroons capability.
3c2855a VFS-1223 Add a refreshing macaroons capability.
968a835 VFS-1235 Change protocol to support file operations.
ba7a1b5 VFS-1235 Change protocol to support file operations.
d69169c VFS-1235 Add protocol for operations on regular files.
055870f VFS-1217 Build messages NIF through CMake.
44e3dfe Merge pull request #87 in VFS/clproto from feature/VFS-1147-first-operations-on-directories to develop
8db7fab VFS-1153 Add Rename and ChangeMode messages.
0d9f35f VFS-1153 Add Rename and ChangeMode messages.
6513820 VFS-1160 Pull in erlang-tls.
305846f VFS-1160 Pull in erlang-tls.
5a79af5 add ChangeMode and Rename messages
647b045 VFS-1147 fix ambiguous file entry
cb6d5f3 Merge remote-tracking branch 'origin/develop' into feature/VFS-1147-first-operations-on-directories
f06106b Merge pull request #86 in VFS/clproto from feature/VFS-1145-ssl2-integrated-with-oneprovider to develop
354be43 VFS-1147 Fix compilation.
3ab63b5 VFS-1147 Change FileChildren message structure.
68da8d5 Merge branch 'feature/VFS-1147-first-operations-on-directories_merge' of ssh://git.plgrid.pl:7999/vfs/clproto into feature/VFS-1147-first-operations-on-directories
85b8d0e VFS-1153 Add new FUSE messages domain objects.
158ec3b VFS-1147 Add name to FileAttr message.
2f770d5 VFS-1147 Change FileChildren message format.
61ab98b VFS-1147 Add UUID to file attr.
39844f5 VFS-1147 Using parent UUID for directory creation.
46b5639 VFS-1147 Add communication protocol between FUSE client and the server.
7766498 VFS-1145 Remove oneproxy messages.
1d5c47a Merge pull request #85 in VFS/clproto from feature/VFS-1129-packages-deb-and-rpm to develop
62ea25f VFS-1129 Revert gpb update, do not delete priv/vsn.git during clean.
007acd1 VFS-1129 Update gpb.
281c0f3 Merge pull request #84 in VFS/clproto from feature/VFS-1115-rpm-packages to develop
010fc07 VFS-1115 Update gpb.
6d2523e Merge pull request #83 in VFS/clproto from feature/VFS-1111-communication-layer-unit-tests to develop
8820963 Merge remote-tracking branch 'origin/develop' into feature/VFS-1111-communication-layer-unit-tests
8ab110b VFS-1111 Implement Translator layer tests.
1b807c3 Merge pull request #82 in VFS/clproto from feature/VFS-1098-dialyzer-works-for-gr to develop
d67ad39 VFS-1098 Apply recommended changes.
36d56fe VFS-1098 Generating Erlang NIFs.
6268a5f VFS-1098 Add oneproxy messages.
d657d2e VFS-1098 Change Protocol Buffers compiler.
0b8a612 VFS-1098 Create rebar application.
1861cd4 Merge pull request #80 in VFS/clproto from feature/VFS-1016-new-messages-handling-with-streaming to develop
d4ea68b Merge commit '5369641d1ca1b989f1d9594768f5fefae0566332' into feature/VFS-1016-new-messages-handling-with-streaming
bb9954e Merge remote-tracking branch 'origin/feature/VFS-1034-oc-protocol-integration' into feature/VFS-1016-new-messages-handling-with-streaming
a5acf7c Merge pull request #78 in VFS/clproto from VFS-1035-Add-CMakeLists-to-protocol to develop
690de64 Merge pull request #79 in VFS/clproto from feature/VFS-1037-op-communicator-performance-test to develop
3800374 VFS-1037 naming changes
d1ba29d VFS-1037 doc
292f02e VFS-1037 repair invalid imports
845b3b6 VFS-1037 protocol version messages added as oneof client/server message
c03a2a5 VFS-1037 rename ping_messages to diagnostic_messages,add 'GetProtocolVersion' message
b8393dd VFS-1037 rename ping_messages to diagnostic_messages,add 'GetProtocolVersion' message
9899db7 VFS-1037 doc update
7a1ea8f VFS-1016 Improve protocol.
684ad1b Merge pull request #77 in VFS/clproto from VFS-1035-Add-CMakeLists-to-protocol to feature/VFS-1034-oc-protocol-integration
be6f29f VFS-1035 Rewrite CMakeLists to allow building helpers as subproject.
f53a2c5 VFS-1034 Fix protocol compilation.
803f77a VFS-1037 Data message
cafd2cc ping messages
c421abf Merge pull request #76 in VFS/clproto from feature/VFS-1009-op-new-protocol-handler to develop
33a8317 beautify protocol v2
4c8508a beautify protocol
8584c8a VFS-997 Add stream message and descriptions + refactoring.
4b27927 change type od message_id from uint64 to bytes
9423229 change handshake message
e63b893 certificate msg extended
5f3db6c remove header
6f2b815 remove HandshakeAcknowledgement
2d2761d typo fix
2e5237e new handshake messages
2ea50b8 VFS-997 Extend protocol messages.
cbe54db Merge branch 'feature/VFS-1009-op-new-protocol-handler' of ssh://git.plgrid.pl:7999/vfs/clproto into feature/VFS-1005-new-protocol-oc-op
2b37656 rename 'oneof' messages
0069f68 add new proto file aggregating server and client messages
cfb51b4 remove HandshakeRequest data
2b72803 VFS-997 Add communication messages.
5ecbf14 Merge pull request #75 in VFS/clproto from feature/VFS-1005-new-protocol-oc-op to develop
fcd7b8b VFS-1005 Apply recommended changes.
b73c8bd VFS-1005 Minor fix for ServerMessage.
27bde46 VFS-1005 Change wrapping message structure.
613c3a8 VFs-1005 Add partial message mechanism.
50e3537 VFS-1005 Fix Erlang compilation errors.
6260815 VFS-1005 New protocol first implementation.
4bf6ec3 Merge pull request #68 in VFS/clproto from feature/VFS-960-access-to-fiemaps to develop
cbdfa01 GetFileBlockMap change uuid to logical name
a61592d GetFileBlockMap and FileBlockMap messages
d5e2d40 Merge pull request #67 in VFS/clproto from feature/VFS-936-async-update-for-file-attributes to develop
c84f2f9 VFS-936 add uuid field to file attributes
6607496 Merge pull request #66 in VFS/clproto from feature/VFS-931-fsmap-integration-in-fuse-client to develop
7d8a5eb Merge branch 'develop' of ssh://git.plgrid.pl:7999/vfs/clproto into feature/VFS-931-fsmap-integration-in-fuse-client
5d9b1b7 Merge pull request #65 in VFS/clproto from feature/VFS-932-block-info-in-events to develop
924cd10 VFS-931 Update BlocksAvailable message.
85b835c VFS-931 Add UpdateFileBlockMap message.
7e352e4 VFS-932 Change event message.
d30494b VFS-932 Change event message.
6df0c5b VFS-932 Change event message.
b1dbeec VFS-932 Add block properties to event message.
8f9daaa Merge pull request #64 in VFS/clproto from feature/VFS-921-rtransfer-goes-to-fslogic to develop
8cffa61 remove relative truncate
aae8331 add size_relative flag to FileTruncated message
a3614af typo fix
b129904 FileTruncated message
527ce4e FileBlockModified message
97fb9d7 SynchronizeFileBlock message
fbf1457 Merge pull request #59 in VFS/clproto from feature/VFS-888-map-files-to-blocks-for-fuse-and to develop
9e59d72 Merge remote-tracking branch 'origin/develop' into feature/VFS-888-map-files-to-blocks-for-fuse-and
68c7f87 VFS-888 Set 'blocks' as a repeated field.
eec028d Merge pull request #58 in VFS/veilprotocol from feature/VFS-858-new-cdmi-features-user-requirements to develop
4ecf392 VFS-888 Change identification fields of RequestFileBlock.
606de6b VFS-888 Add block-related messages and message fields.
96e3bfa Merge branch 'develop' into feature/VFS-858-new-cdmi-features-user-requirements
320d88c add acl flag
a8bc820 Merge pull request #57 in VFS/veilprotocol from feature/VFS-837-veil-to-onedata to develop
98fd52a VFS-837 Final renaming.
1351802 Merge pull request #56 in VFS/veilprotocol from feature/VFS-837-veil-to-onedata to develop
8fec391 VFS-837 Make onedata start with an uppercase letter.
d77f98f VFS-837 Refactor readme.
d7ea703 VFS-837 Rename namespace.
0a96244 VFS-837 Change from 'veil' to 'onedata'.
6751fe1 children count messages
21b6448 new acl messages
b7ad0a7 Merge pull request #54 in VFS/veilprotocol from feature/VFS-830-dokladne-przejrzenie-dokumentacji to develop
947a614 Merge branch 'develop' into feature/VFS-830-dokladne-przejrzenie-dokumentacji
cd83847 turn back develop changes
6ffbe83 Merge pull request #53 in VFS/veilprotocol from feature/VFS-828-zmiana-sposobu-uwierzytelnienia-tokenem to develop
2c2fe29 Merge pull request #50 in VFS/veilprotocol from feature/VFS-829-move-between-providers to develop
c1958c5 Merge pull request #51 in VFS/veilprotocol from master to develop
bbbbbaa VFS-828 Remove identity field in HandshakeRequest.
d6c8b3a VFS-829: fix typo
52aeab3 revert newest develop changes
b8a16f8 extended Attrs api
f1a5e5c Merge pull request #49 in VFS/veilprotocol from feature/VFS-829-move-between-providers to develop
278cec8 Merge pull request #48 in VFS/veilprotocol from feature/VFS-820-zastapic-obecne-checki-uprawnien to develop
2c6199a Merge pull request #47 in VFS/veilprotocol from feature/VFS-781-uwierzytelnienie-klienta-przy-pomocy to develop
ab8da14 VFS-829: fix compile
b0a4b59 VFS-829: fix compile
d1bc237 VFS-829: add DirEntry to protocol
57ef0e7 VFS-829: add DirEntry to protocol
61faf51 VFS-820, change message name
a8472c1 Merge branch 'feature/VFS-781-uwierzytelnienie-klienta-przy-pomocy' of ssh://git.plgrid.pl:7999/vfs/veilprotocol into feature/VFS-820-zastapic-obecne-checki-uprawnien
9cb05c4 VFS-820, add CheckPerms message
bdf9d21 VFS-781 Fix protocol.
2202298 Merge remote-tracking branch 'origin/develop' into feature/VFS-781-uwierzytelnienie-klienta-przy-pomocy
e0922ca Merge pull request #46 in VFS/veilprotocol from feature/VFS-784-obsuga-cdmi_capabilities to develop
4cd3381 VFS-781 Add an identity field for handshake request.
9440a98 GetFileUuid and FileUuid messages added
8dcf62c Merge pull request #45 in VFS/veilprotocol from feature/VFS-754-dostep-zdalny-do-innego-providera to develop
8590cc1 VFS-754: add cluster proxy getattr
47b8904 VFS-754: add cluster proxy getattr
0de5be7 Merge remote-tracking branch 'origin/develop' into feature/VFS-754-dostep-zdalny-do-innego-providera
cfbaf77 VFS-754: add message decoder to answer message
ef27ce5 Merge pull request #40 in VFS/veilprotocol from release-1.0 to develop
a03f86a Merge pull request #39 in VFS/veilprotocol from release-1.0 to master
939895c Merge pull request #38 in VFS/veilprotocol from bugfix/VFS-751-release-1.5-wypuszczony to release-1.0
e4dc26e Release notes updatd
8670fb4 Merge pull request #37 in VFS/veilprotocol from bugfix/VFS-751-release-1.5-wypuszczony to release-1.0
b77373b Release notes added
f1355db Merge pull request #36 in VFS/veilprotocol from feature/VFS-749-clusterproxy-uzywany-gdy-brak-accessu to develop
4dc1ed0 VFS-754: add global user id to cluster message
84322ed VFS-754: add ProviderMsg
f5394d9 VFS-754: add access tokent to cluster message
4d44532 Merge branch 'feature/VFS-749-clusterproxy-uzywany-gdy-brak-accessu' into feature/VFS-754-dostep-zdalny-do-innego-providera
944861f VFS-754: make space_id optional
0f61799 VFS-749: add ClusterProxy context info
d17ccb8 VFS-754: add space_id to RFM
76c5dff Merge pull request #35 in VFS/veilprotocol from feature/gui_release_to_develop to develop
b41dd32 Merge branch 'release-1.0' into feature/gui_release_to_develop
41d9a76 Merge pull request #34 in VFS/veilprotocol from feature/VFS-731-wysyanie-poziomu-uprawnien-pliku to release-1.0
184b766 add mode to CreateFile message
25188df Merge pull request #33 in VFS/veilprotocol from release-1.0 to develop
37b1a8d Merge pull request #32 in VFS/veilprotocol from bugfix/VFS-592-dostep-do-pliku-niezgodny-z-ustawionym to release-1.0
68962ce default open_mode msg changed from "none" to ""
fe42fe9 Merge branch 'release-1.0' into bugfix/VFS-592-dostep-do-pliku-niezgodny-z-ustawionym
74f49cb Merge pull request #31 in VFS/veilprotocol from bugfix/VFS-608-niemozliwosc-zarejestrowania-DN to release-1.0
681cdfe open_mode optional parameter added to GetFileLocation msg
e5424af VFS-608, fix naming
194e6d0 VFS-608, add fields to proto to handle cert verification
d1395fb VFS-608, add error description field to Answer record
a459825 Merge pull request #30 in VFS/veilprotocol from VFS-555 to develop
5677ce6 [VFS-555] typo fix
0862a00 [VFS-555] EventStreamConfig extended
e420048 Merge pull request #27 in VFS/veilprotocol from VFS-489 to master
ee7b249 VFS-489 Message fix.
2263e19 VFS-489 Make some message fields required.
af6e6b8 VFS-489 Create more specific storage test messages.
e86b601 VFS-489 Direct IO storage message refactored.
ceaedf2 VFS-489 Direct IO storage message added.
ec8208e VFS-489 Storage test messages refactored.
fdf35b6 VFS-489 Storage test messages added.
4db85aa Merge pull request #26 in VFS/veilprotocol from VFS-482 to master
b07e7bd Merge branch 'VFS-482' of ssh://git.plgrid.pl:7999/vfs/veilprotocol into VFS-482
abc677e Generic event message added
f517338 Merge pull request #24 in VFS/veilprotocol from VFS-443-centralny-logger-dla-clientow to master
81fd5c1 Merge pull request #25 in VFS/veilprotocol from VFS-441 to master
680c66c [VFS-441] comment added
c71b9ea VFS-443 Add logging protocol.
ecae432 [VFS-441] EventTransformer added
cf0ed2e Merge pull request #23 in VFS/veilprotocol from VFS-441 to master
26e569e [VFS-441] pushmessage message removed
578c1e9 [VFS-441] Comments for EventStreamConfig
dd4be71 [VFS-441] eventaggregatorconfig message extended
37c9a41 [VFS-441] client fetch event producer configuration on startup
06caeb6 [VFS-441] protocol buffer messages for events improved
ce371ef [VFS-413] messages for events subscription added
9d289fd Merge pull request #22 in VFS/veilprotocol from VFS-442 to master
e0b9ed9 VFS-442 Add answer field to StatFSInfo message.
b001a78 Merge pull request #21 in VFS/veilprotocol from VFS-442 to master
aef57ff VFS-442 Merge veilprotocol messages.
7e36203 VFS-442 GetFilesSize and FilesSizeInfo messages added.
0aa0848 VFS-442 GetQuota and QuotaInfo messages added.
1e45be5 Merge pull request #20 in VFS/veilprotocol from VFS-435-problem-z-wyswietlaniem-duzych-plikow to master
32aaf5e another changes in size type from int32 to int64
45b786e size type changed from int32 to int64
87ac2f6 Merge pull request #19 in VFS/veilprotocol from VFS-240 to master
995da9b [VFS-240] Message CreateFileAck changed
66c68e3 [VFS-240] CreateFileAck message added
8548237 Merge pull request #18 in VFS/veilprotocol from VFS-356 to master
8a2eb34 ChangePermsAtStorage message added
ec4d3e4 Merge pull request #17 in VFS/veilprotocol from VFS-211 to master
1402c88 VFS-211 Links field to files attribute added.
e808f04 Merge pull request #16 in VFS/veilprotocol from VFS-264 to master
58d5334 Merge pull request #15 in VFS/veilprotocol from VFS-252 to master
d11ae1d Merge pull request #13 in VFS/veilprotocol from VFS-260 to master
2645d9b Merge pull request #12 in VFS/veilprotocol from VFS-167 to master
34bba96 Merge pull request #11 in VFS/veilprotocol from VFS-162 to master
5f631d2 Merge pull request #10 in VFS/veilprotocol from VFS-159 to master
b77991a Merge pull request #9 in VFS/veilprotocol from VFS-162 to master
b1578ab Merge pull request #8 in VFS/veilprotocol from VFS-156 to master
41bc0be Merge pull request #7 in VFS/veilprotocol from VFS-127 to master
4781952 Merge pull request #6 in VFS/veilprotocol from VFS-113 to master
11d5d1a Merge pull request #5 in VFS/veilprotocol from VFS-101 to master
72bf94c fuse messages updated
1956dbb Merge pull request #4 from VFS-80,85 to master
9b65f25 FileChildren fix
1ff7d28 Merge pull request #3 from VFS-80 to master
cb54b30 decoder fields corrected
4048cfb Merge branch 'VFS-80' of ssh://git.plgrid.pl:7999/VFS/veilprotocol into VFS-80
b9a67a5 Added decoder_name and messages for directory creation and location validity info
9f660cf Added decoder_name and messages for directory creation and location validity info
1b7b40b Merge pull request #1 from VFS-80 to master
295be28 fuse messages
e85f681 fuse messages
6dcc3aa Initial Commit

git-subtree-dir: helpers
git-subtree-split: 149b44a4eb29b6edb331a8feb053b62e89c32379